// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = never
type PageRoutes = "/" | "/auth/callback" | "/employee" | "/employee/estimates" | "/employee/estimates/[estimateId]" | "/employee/estimates/[estimateId]/cost-lines/[costLineId]" | "/employee/estimates/new" | "/employee/expenses" | "/employee/field-reports" | "/employee/followups" | "/employee/invoicing" | "/employee/invoicing/[estimateId]" | "/employee/project/[id]" | "/employee/project/[id]/estimates" | "/employee/project/[id]/expenses" | "/employee/project/[id]/overview" | "/employee/project/[id]/reports" | "/employee/project/[id]/staff" | "/employee/project/[id]/tasks" | "/employee/projects" | "/employee/settings" | "/employee/tasks" | "/employee/time-tracking" | "/login" | "/login/[role]" | "/login/employee" | "/login/manager" | "/login/owner" | "/manager" | "/manager/clients" | "/manager/estimates" | "/manager/expenses" | "/manager/field-reports" | "/manager/followups" | "/manager/invoicing" | "/manager/leads" | "/manager/project/[id]" | "/manager/project/[id]/estimates" | "/manager/project/[id]/expenses" | "/manager/project/[id]/overview" | "/manager/project/[id]/reports" | "/manager/project/[id]/staff" | "/manager/project/[id]/tasks" | "/manager/projects" | "/manager/settings" | "/manager/tasks" | "/manager/time-tracking" | "/owner" | "/owner/clients" | "/owner/estimates" | "/owner/estimates/[estimateId]" | "/owner/estimates/[estimateId]/cost-lines/[costLineId]" | "/owner/estimates/new" | "/owner/expenses" | "/owner/field-reports" | "/owner/followups" | "/owner/invoicing" | "/owner/invoicing/[estimateId]" | "/owner/leads" | "/owner/project/[id]" | "/owner/project/[id]/estimates" | "/owner/project/[id]/expenses" | "/owner/project/[id]/overview" | "/owner/project/[id]/reports" | "/owner/project/[id]/staff" | "/owner/project/[id]/tasks" | "/owner/projects" | "/owner/settings" | "/owner/staff" | "/owner/tasks" | "/owner/time-tracking" | "/reset-password"
type LayoutRoutes = never
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/auth/callback": {}
  "/employee": {}
  "/employee/estimates": {}
  "/employee/estimates/[estimateId]": { "estimateId": string; }
  "/employee/estimates/[estimateId]/cost-lines/[costLineId]": { "estimateId": string; "costLineId": string; }
  "/employee/estimates/new": {}
  "/employee/expenses": {}
  "/employee/field-reports": {}
  "/employee/followups": {}
  "/employee/invoicing": {}
  "/employee/invoicing/[estimateId]": { "estimateId": string; }
  "/employee/project/[id]": { "id": string; }
  "/employee/project/[id]/estimates": { "id": string; }
  "/employee/project/[id]/expenses": { "id": string; }
  "/employee/project/[id]/overview": { "id": string; }
  "/employee/project/[id]/reports": { "id": string; }
  "/employee/project/[id]/staff": { "id": string; }
  "/employee/project/[id]/tasks": { "id": string; }
  "/employee/projects": {}
  "/employee/settings": {}
  "/employee/tasks": {}
  "/employee/time-tracking": {}
  "/login": {}
  "/login/[role]": { "role": string; }
  "/login/employee": {}
  "/login/manager": {}
  "/login/owner": {}
  "/manager": {}
  "/manager/clients": {}
  "/manager/estimates": {}
  "/manager/expenses": {}
  "/manager/field-reports": {}
  "/manager/followups": {}
  "/manager/invoicing": {}
  "/manager/leads": {}
  "/manager/project/[id]": { "id": string; }
  "/manager/project/[id]/estimates": { "id": string; }
  "/manager/project/[id]/expenses": { "id": string; }
  "/manager/project/[id]/overview": { "id": string; }
  "/manager/project/[id]/reports": { "id": string; }
  "/manager/project/[id]/staff": { "id": string; }
  "/manager/project/[id]/tasks": { "id": string; }
  "/manager/projects": {}
  "/manager/settings": {}
  "/manager/tasks": {}
  "/manager/time-tracking": {}
  "/owner": {}
  "/owner/clients": {}
  "/owner/estimates": {}
  "/owner/estimates/[estimateId]": { "estimateId": string; }
  "/owner/estimates/[estimateId]/cost-lines/[costLineId]": { "estimateId": string; "costLineId": string; }
  "/owner/estimates/new": {}
  "/owner/expenses": {}
  "/owner/field-reports": {}
  "/owner/followups": {}
  "/owner/invoicing": {}
  "/owner/invoicing/[estimateId]": { "estimateId": string; }
  "/owner/leads": {}
  "/owner/project/[id]": { "id": string; }
  "/owner/project/[id]/estimates": { "id": string; }
  "/owner/project/[id]/expenses": { "id": string; }
  "/owner/project/[id]/overview": { "id": string; }
  "/owner/project/[id]/reports": { "id": string; }
  "/owner/project/[id]/staff": { "id": string; }
  "/owner/project/[id]/tasks": { "id": string; }
  "/owner/projects": {}
  "/owner/settings": {}
  "/owner/staff": {}
  "/owner/tasks": {}
  "/owner/time-tracking": {}
  "/reset-password": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
